import React from "react";
import Box from "../elements/Box";
import theme from "../../theme";

const Colors = () => {
  const { colors } = theme.light;
  return (
    <>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.white}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.white}
        </Box>
        <Box
          bg={colors.grey[0]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[0]}
        </Box>
        <Box
          bg={colors.grey[1]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[1]}
        </Box>
        <Box
          bg={colors.grey[2]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[2]}
        </Box>
        <Box
          bg={colors.grey[3]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[3]}
        </Box>
        <Box
          bg={colors.grey[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[4]}
        </Box>
        <Box
          bg={colors.grey[5]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[5]}
        </Box>
        <Box
          bg={colors.grey[6]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[6]}
        </Box>
        <Box
          bg={colors.black}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.black}
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.blue[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[0]}
        </Box>
        <Box
          bg={colors.blue[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[1]}
        </Box>
        <Box
          bg={colors.blue[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[2]}
        </Box>
        <Box
          bg={colors.blue[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[3]}
        </Box>
        <Box
          bg={colors.blue[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[4]}
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.green[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[0]}
        </Box>
        <Box
          bg={colors.green[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[1]}
        </Box>
        <Box
          bg={colors.green[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[2]}
        </Box>
        <Box
          bg={colors.green[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[3]}
        </Box>
        <Box
          bg={colors.green[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[4]}
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.red[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[0]}
        </Box>
        <Box
          bg={colors.red[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[1]}
        </Box>
        <Box
          bg={colors.red[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[2]}{" "}
        </Box>
        <Box
          bg={colors.red[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[3]}
        </Box>
        <Box
          bg={colors.red[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[4]}
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.yellow[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[0]}
        </Box>
        <Box
          bg={colors.yellow[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[1]}
        </Box>
        <Box
          bg={colors.yellow[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[2]}
        </Box>
        <Box
          bg={colors.yellow[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[3]}
        </Box>
        <Box
          bg={colors.yellow[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[4]}
        </Box>
      </Box>
    </>
  );
};

export default Colors;

export const MainColors = () => {
  const { colors } = theme.light;

  return (
    <>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.color}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Color
        </Box>
        <Box
          bg={colors.bg}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Bg
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.light}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Light
        </Box>
        <Box
          bg={colors.dark}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Dark
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.primary}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Primary
        </Box>
        <Box
          bg={colors.secondary}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Secondary
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.info}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Info
        </Box>
        <Box
          bg={colors.success}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Success
        </Box>
        <Box
          bg={colors.warning}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Warning
        </Box>
        <Box
          bg={colors.danger}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Danger
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.link}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Link
        </Box>
        <Box
          bg={colors.muted}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Muted
        </Box>
      </Box>
    </>
  );
};

export const MainColorsDark = () => {
  const { colors } = theme.dark;

  return (
    <>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.color}
          color={colors.grey[6]}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Color
        </Box>
        <Box
          bg={colors.bg}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Bg
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.light}
          color={colors.grey[6]}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Light
        </Box>
        <Box
          bg={colors.dark}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Dark
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.primary}
          color={colors.grey[6]}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Primary
        </Box>
        <Box
          bg={colors.secondary}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Secondary
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.info}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Info
        </Box>
        <Box
          bg={colors.success}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Success
        </Box>
        <Box
          bg={colors.warning}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Warning
        </Box>
        <Box
          bg={colors.danger}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Danger
        </Box>
      </Box>
      <Box flex flexWrap="wrap">
        <Box
          bg={colors.link}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Link
        </Box>
        <Box
          bg={colors.muted}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Muted
        </Box>
      </Box>
    </>
  );
};
