import React from "react";
import Box from "../elements/Box";
import theme from "../../theme";

const Colors = () => {
  const { colors } = theme;
  return (
    <>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={colors.white}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.white}
        </Box>
        <Box
          bg={colors.grey[0]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[0]}
        </Box>
        <Box
          bg={colors.grey[1]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[1]}
        </Box>
        <Box
          bg={colors.grey[2]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[2]}
        </Box>
        <Box
          bg={colors.grey[3]}
          color={colors.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[3]}
        </Box>
        <Box
          bg={colors.grey[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[4]}
        </Box>
        <Box
          bg={colors.grey[5]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[5]}
        </Box>
        <Box
          bg={colors.grey[6]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.grey[6]}
        </Box>
        <Box
          bg={colors.black}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.black}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={colors.blue[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[0]}
        </Box>
        <Box
          bg={colors.blue[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[1]}
        </Box>
        <Box
          bg={colors.blue[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[2]}
        </Box>
        <Box
          bg={colors.blue[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[3]}
        </Box>
        <Box
          bg={colors.blue[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.blue[4]}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={colors.green[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[0]}
        </Box>
        <Box
          bg={colors.green[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[1]}
        </Box>
        <Box
          bg={colors.green[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[2]}
        </Box>
        <Box
          bg={colors.green[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[3]}
        </Box>
        <Box
          bg={colors.green[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.green[4]}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={colors.red[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[0]}
        </Box>
        <Box
          bg={colors.red[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[1]}
        </Box>
        <Box
          bg={colors.red[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[2]}{" "}
        </Box>
        <Box
          bg={colors.red[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[3]}
        </Box>
        <Box
          bg={colors.red[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.red[4]}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={colors.yellow[0]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[0]}
        </Box>
        <Box
          bg={colors.yellow[1]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[1]}
        </Box>
        <Box
          bg={colors.yellow[2]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[2]}
        </Box>
        <Box
          bg={colors.yellow[3]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[3]}
        </Box>
        <Box
          bg={colors.yellow[4]}
          color={colors.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={2}
          py={4}
          textAlign="center">
          {colors.yellow[4]}
        </Box>
      </Box>
    </>
  );
};

export default Colors;

export const MainColors = () => {
  const { light } = theme.colors.schemes;

  return (
    <>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={light.color}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Color {light.color}
        </Box>
        <Box
          bg={light.bg}
          color={light.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Bg {light.bg}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={light.light}
          color={light.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Light {light.light}
        </Box>
        <Box
          bg={light.dark}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Dark {light.dark}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={light.primary}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Primary {light.primary}
        </Box>
        <Box
          bg={light.secondary}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Secondary {light.secondary}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={light.info}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Info {light.info}
        </Box>
        <Box
          bg={light.success}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Success {light.success}
        </Box>
        <Box
          bg={light.warning}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Warning {light.warning}
        </Box>
        <Box
          bg={light.danger}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Danger {light.danger}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={light.link}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Link {light.link}
        </Box>
        <Box
          bg={light.muted}
          color={light.light}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Muted {light.muted}
        </Box>
      </Box>
    </>
  );
};

export const MainColorsDark = () => {
  const { dark } = theme.colors.schemes;

  return (
    <>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={dark.color}
          color={dark.grey[6]}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Color {dark.color}
        </Box>
        <Box
          bg={dark.bg}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Bg {dark.bg}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={dark.light}
          color={dark.grey[6]}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Light {dark.light}
        </Box>
        <Box
          bg={dark.dark}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Dark {dark.dark}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={dark.primary}
          color={dark.grey[6]}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Primary {dark.primary}
        </Box>
        <Box
          bg={dark.secondary}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Secondary {dark.secondary}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={dark.info}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Info {dark.info}
        </Box>
        <Box
          bg={dark.success}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Success {dark.success}
        </Box>
        <Box
          bg={dark.warning}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Warning {dark.warning}
        </Box>
        <Box
          bg={dark.danger}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Danger {dark.danger}
        </Box>
      </Box>
      <Box display="flex" flexWrap="wrap">
        <Box
          bg={dark.link}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Link {dark.link}
        </Box>
        <Box
          bg={dark.muted}
          color={dark.color}
          flexBasis={0}
          flexGrow={1}
          fontSize={[0]}
          fontWeight={[3]}
          m={1}
          px={1}
          py={4}
          textAlign="center">
          Muted {dark.muted}
        </Box>
      </Box>
    </>
  );
};
